// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const { PrismaBetterSqlite3 } = require("@prisma/adapter-better-sqlite3");
const { PrismaClient } = require("../../generated/prisma");

const connectionString = process.env.DATABASE_URL;

const adapter = new PrismaBetterSqlite3({ url: connectionString });
const prisma = new PrismaClient({ adapter });

module.exports = { prisma };
