###
POST /auth/register
Host: localhost:8000
Content-Type: application/json

{
    "fullname": "fiki",
    "email": "fiki12345678@mail.com",
    "password": "12345678"
}

###
POST /auth/login
Host: localhost:8000
Content-Type: application/json

{
    "email": "fiki12345678@mail.com",
    "password": "12345678"
}


/// products
###
GET /products
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY0MTcwNzc5LCJleHAiOjE3NjQxNzE2Nzl9.hStN2_bDZnjXxYjngNw2rBPd5TbmfQhYXmSDbVOCcSU

###
GET /products/1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY0MTcwNzc5LCJleHAiOjE3NjQxNzE2Nzl9.hStN2_bDZnjXxYjngNw2rBPd5TbmfQhYXmSDbVOCcSU



/// create products
###
POST /products
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY0MTUyNTgxLCJleHAiOjE3NjQyMDY1ODF9.tCoRfQgNE9bREp5oPubwI2ZVwB88YEEY2WTcwSsluIk


{
    "name": "mie ayam",
    "price": 12000
}

/// edit products
### 
PATCH /products/4
Host: localhost:8000
Content-Type: application/json

{
    "name": "indomie",
    "price": 2000
}

/// delete products
###
DELETE /products/3
Host: localhost:8000
