###
POST /auth/register
Host: localhost:8000
Content-Type: application/json

{
    "fullName": "fiki",
    "email": "fiki@mail.com",
    "password": "12345678"
}

###
POST /auth/login
Host: localhost:8000
Content-Type: application/json

{
     "email": "fiki@mail.com",
     "password": "12345678"
}


/// products
###
GET /products
Host: localhost:8000

###
GET /products/4
Host: localhost:8000


/// create products
###
POST /products
Host: localhost:8000
Content-Type: application/json

{
    "name": "mie ayam",
    "price": 12000
}

/// edit products
### 
PATCH /products/4
Host: localhost:8000
Content-Type: application/json

{
    "name": "indomie",
    "price": 2000
}

/// delete products
###
DELETE /products/3
Host: localhost:8000
